### ISSUE TITLE
请问可以提供APK安装包么？

### ISSUE THREAD

**Issue by lsl330** [qdsfdhvh/DanDanPlayForTVPersonal#1]
另外能不能直接播放局域网视频（弹幕和视频同名放在一起）

**Comment by qdsfdhvh** [comment]
> 另外能不能直接播放局域网视频（弹幕和视频同名放在一起）

不能播放局域网视频；这个项目并不成熟，目前只适合开发者之间代码相互参考，不太适合日常使用。

**Comment by lsl330** [comment]
好吧，希望以后能完善，支持！tv端目前好像没有好的弹幕播放器

**Comment by qdsfdhvh** [comment]
@lsl330 弹弹官方正在做，应该快了。
